import Head from "next/head";
import { Header } from "src/components";

const Home = () => {
  return (
    <div className="relative h-[200vh]">
      <Head>
        <title>Home | Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main>
        {/* Hero */}
        <section>
          {/* Row */}
          {/* Big Row */}
          {/* Row */}
          {/* Big Row */}
        </section>
      </main>
    </div>
  );
};

export default Home;
